### pytorch_tutorial_tensor

In [8]:
import torch
torch.__version__

'1.12.1+cu116'

In [15]:
t1 = torch.empty(4,2)
t2 = torch.zeros(4,2, dtype = torch.long)
t2 = torch.tensor([3, 2.3])
print(t1)
print(t2)
print(t1.shape)
print(t1.dtype)
print(t1.device)

tensor([[6.3021e-14, 3.0660e-41],
        [4.3734e+22, 3.0660e-41],
        [4.4842e-44, 0.0000e+00],
        [6.7262e-44, 0.0000e+00]])
tensor([3.0000, 2.3000])
torch.Size([4, 2])
torch.float32
cpu


In [16]:
t2 = torch.rand(2)
print("t2: ")
print(t2)
print(t2.shape)

print("\n---------after unsqueeze-------")
t2_add_rank = t2.unsqueeze(0)
print(t2_add_rank)
print(t2_add_rank.shape)

t2: 
tensor([0.9408, 0.2502])
torch.Size([2])

---------after unsqueeze-------
tensor([[0.9408, 0.2502]])
torch.Size([1, 2])


In [19]:
 x = torch.rand(4,2)
 print(x)

tensor([[0.7620, 0.9470],
        [0.5952, 0.5113],
        [0.8691, 0.5554],
        [0.0809, 0.9402]])


In [22]:
x = torch.zeros(4,2, dtype = torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [24]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


In [25]:
x = x.new_ones(2, 4, dtype =torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [26]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[-0.7978,  1.8297,  1.8322,  1.3281],
        [-0.0141, -0.2452,  0.3003,  0.0311]])


In [27]:
print(x.size())

torch.Size([2, 4])


In [32]:
ft = torch.cuda.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)
print(ft.double())

tensor([1., 2., 3.], device='cuda:0')
torch.float32
tensor([1., 2., 3.], device='cuda:0', dtype=torch.float64)


In [34]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.3001])
0.3001250922679901
torch.float32
cuda


In [37]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
x = x.to(device)
print(x)
z = x + y
z = z.to('cpu', torch.double)
print(z)

cuda
tensor([0.3001], device='cuda:0')
tensor([1.3001], dtype=torch.float64)


In [41]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [40]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [42]:
t2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [44]:
t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [45]:
t4 = torch.tensor([[[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]]],
[[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]]],
[[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]],
[[1,2,3],[4,5,6],[7,8,9]]]])
print(t4.ndim)
print(t4.shape)
print(t4)

4
torch.Size([3, 3, 3, 3])
tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])


In [46]:
import math

a= torch.rand(1,2) * 2 -1
print(a)

tensor([[0.7324, 0.6382]])


In [48]:
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[0.7324, 0.6382]])
tensor([[1., 1.]])
tensor([[0., 0.]])
tensor([[0.5000, 0.5000]])


In [51]:
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,3])))

tensor(0.0666)
tensor(0.4674)
tensor([1, 2, 3])


In [53]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.4845, 0.0280],
        [0.5463, 0.3439]])
torch.return_types.max(
values=tensor([0.5463, 0.3439]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([0.4845, 0.5463]),
indices=tensor([0, 0]))


In [54]:
x = torch.rand(2,2)
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.1028, 0.0563],
        [0.9951, 0.5674]])
torch.return_types.min(
values=tensor([0.1028, 0.0563]),
indices=tensor([0, 0]))
torch.return_types.min(
values=tensor([0.0563, 0.5674]),
indices=tensor([1, 1]))


In [59]:
x = torch.rand(2,2)
y = torch.rand(2,2)
result = torch.empty(2,4)
torch.add(x,y, out = result)
print(result)

tensor([[1.6370, 1.2032],
        [1.3230, 1.3038]])


/tmp/ipykernel_8643/2856573021.py:4: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:17.)
  torch.add(x,y, out = result)


In [60]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.8979, 0.6082],
        [0.8807, 0.6996]])
tensor([[0.7391, 0.5951],
        [0.4424, 0.6042]])
tensor([[1.6370, 1.2032],
        [1.3230, 1.3038]])


In [4]:
t4 = torch.rand(192) # 3*8*8
print(t4.shape)

t4 = t4.reshape(3,8,8)
print("\n---after reshape----")
print(t4.shape)

t4 = t4.permute(1,2,0)
print("\n---after permute----")
print(t4.shape)

torch.Size([192])

---after reshape----
torch.Size([3, 8, 8])

---after permute----
torch.Size([8, 8, 3])


In [5]:
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
t1_gpu = t1.cuda(device)
print(t1_gpu)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:1')


In [6]:
torch.cuda.is_available()

True