### pytorch_tutorial_tensor

In [1]:
import torch

In [2]:
print(torch.__version__)

t1 = torch.zeros(4,3)
print(t1)
print(t1.shape)
print(t1.dtype)
print(t1.device)

1.12.1+cu116
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([4, 3])
torch.float32
cpu


In [3]:
t2 = torch.rand(2)
print("t2: ")
print(t2)
print(t2.shape)

print("\n---------after unsqueeze-------")
t2_add_rank = t2.unsqueeze(0)
print(t2_add_rank)
print(t2_add_rank.shape)

t2: 
tensor([0.0653, 0.6267])
torch.Size([2])

---------after unsqueeze-------
tensor([[0.0653, 0.6267]])
torch.Size([1, 2])


In [4]:
t4 = torch.rand(192) # 3*8*8
print(t4.shape)

t4 = t4.reshape(3,8,8)
print("\n---after reshape----")
print(t4.shape)

t4 = t4.permute(1,2,0)
print("\n---after permute----")
print(t4.shape)

torch.Size([192])

---after reshape----
torch.Size([3, 8, 8])

---after permute----
torch.Size([8, 8, 3])


In [5]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
t1_gpu = t1.cuda(device)
print(t1_gpu.device)
print(t1.device)

cuda:0
cpu


In [7]:
torch.cuda.is_available()

True