### pytorch_tutorial_tensor

In [6]:
import torch

In [7]:
print(torch.__version__)

t1 = torch.zeros(4,3)
print(t1)
print(t1.shape)
print(t1.dtype)
print(t1.device)

1.13.0.dev20220824
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([4, 3])
torch.float32
cpu


In [8]:
t2 = torch.rand(2)
print("t2: ")
print(t2)
print(t2.shape)

print("\n---------after unsqueeze-------")
t2_add_rank = t2.unsqueeze(0)
print(t2_add_rank)
print(t2_add_rank.shape)

t2: 
tensor([0.5857, 0.5779])
torch.Size([2])

---------after unsqueeze-------
tensor([[0.5857, 0.5779]])
torch.Size([1, 2])


In [9]:
t4 = torch.rand(192) # 3*8*8
print(t4.shape)

t4 = t4.reshape(3,8,8)
print("\n---after reshape----")
print(t4.shape)

t4 = t4.permute(1,2,0)
print("\n---after permute----")
print(t4.shape)

torch.Size([192])

---after reshape----
torch.Size([3, 8, 8])

---after permute----
torch.Size([8, 8, 3])


In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
t1_gpu = t1.cuda(device)
print(t1_gpu.device)
print(t1.device)

/home/hojun/miniconda3/envs/torch/lib/python3.10/site-packages/torch/cuda/__init__.py:150: UserWarning: 
NVIDIA GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
