In [1]:
import torch

In [2]:
import numpy as np 

In [3]:
torch.__version__

'1.12.1+cu116'

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int64')

In [6]:
x = torch.from_numpy(arr)

In [7]:
type(x)

torch.Tensor

In [8]:
torch.as_tensor(arr).dtype

torch.int64

In [9]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
arr2d.reshape(4,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
x2 = torch.from_numpy(arr2d)
x2

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [12]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_tensor = torch.Tensor(my_arr) # no take effected by numpy array
my_other_tensor = torch.from_numpy(my_arr) # take effected by numpy array

In [14]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_arr[0] =12

In [16]:
my_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
new_arr = np.array([1,2,3])

In [18]:
new_arr.dtype

dtype('int64')

In [19]:
torch.tensor(new_arr)

tensor([1, 2, 3])

In [20]:
torch.Tensor(new_arr) # == floatTensor

tensor([1., 2., 3.])

In [23]:
my_tensor = torch.Tensor(new_arr)

In [25]:
torch.empty(4,2)

tensor([[ 1.7713e-06,  4.5740e-41],
        [-1.0626e-08,  3.0739e-41],
        [ 4.4842e-44,  0.0000e+00],
        [ 1.7937e-43,  0.0000e+00]])

In [27]:
torch.zeros(4,3, dtype =torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
torch.ones(4,3, dtype = torch.int64).dtype

torch.int64

In [33]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [35]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [36]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [41]:
my_tensor = my_tensor.type(torch.int32) # type(~~) change the type
my_tensor.dtype

torch.int32

In [42]:
torch.rand(3,4)

tensor([[0.3809, 0.0694, 0.7577, 0.5791],
        [0.2715, 0.0014, 0.7996, 0.0626],
        [0.6207, 0.2279, 0.6937, 0.0982]])

In [43]:
torch.randn(4,3)

tensor([[ 0.1715,  0.8281,  0.1303],
        [ 0.5465,  0.9292, -0.3427],
        [-0.2788,  0.8613, -0.3768],
        [-0.4309, -0.1350,  0.8641]])

In [44]:
torch.randint(low = 0, high =10, size = (5,5))

tensor([[5, 7, 2, 4, 3],
        [1, 3, 4, 1, 2],
        [5, 5, 8, 3, 0],
        [3, 3, 0, 3, 1],
        [2, 5, 8, 3, 5]])

In [46]:
x =  torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [47]:
torch.rand_like(x)

tensor([[0.8211, 0.6317, 0.1647, 0.7558, 0.9935],
        [0.6412, 0.3790, 0.7043, 0.2579, 0.9212]])

In [48]:
torch.randn_like(x)

tensor([[ 0.5128, -1.5633, -0.5607, -1.1048, -0.5188],
        [ 0.4691,  1.5064,  1.5954, -0.2969,  0.8877]])

In [49]:
torch.randint_like(x, high = 10, low = 1)

tensor([[2., 2., 5., 4., 8.],
        [2., 8., 2., 4., 8.]])

In [50]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])