In [1]:
import torch
import numpy as np

In [2]:
my_tensor = torch.arange(6).reshape(3,2)
my_tensor

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [3]:
my_tensor[1,1]

tensor(3)

In [4]:
my_tensor[1][1]

tensor(3)

In [5]:
type(my_tensor[1,1])

torch.Tensor

In [6]:
my_tensor[:,1]

tensor([1, 3, 5])

In [7]:
my_tensor[:,1:]

tensor([[1],
        [3],
        [5]])

In [8]:
x = torch.arange(10)

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
z = x.view(2,5) # view() takes effect to z (copied by x)

In [13]:
x[0] = 9999

In [14]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [15]:
x = torch.arange(10) 

In [16]:
x.view(2,-1) # need to be /2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
a = torch.tensor([1.,2,3.])
a.dtype

torch.float32

In [19]:
a = torch.tensor([1,2,3])
b= torch.tensor([4,5,6])
a

tensor([1, 2, 3])

In [20]:
b

tensor([4, 5, 6])

In [21]:
torch.add(a,b)

tensor([5, 7, 9])

In [22]:
a = a.mul(b)
a
# a = a ＊ b 

tensor([ 4, 10, 18])

In [23]:
a.mul(b)

tensor([ 16,  50, 108])

In [24]:
a.dot(b)

tensor(174)

In [26]:
a = torch.tensor([[0,2,4], [1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [27]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [29]:
a.shape

torch.Size([2, 3])

In [30]:
b.shape

torch.Size([3, 2])

In [31]:
a.mm(b) ## matrix multiplication

tensor([[56, 62],
        [80, 89]])

In [32]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [33]:
x = torch.Tensor([2,3,4,5])

In [35]:
x.norm() ## square (sum of x^2)

tensor(7.3485)

In [36]:
x.numel() #number of elements

4

In [37]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [38]:
len(a) ## return 2 (number of rows)

2

In [39]:
a.numel()

6