In [1]:
import torch
import numpy as np

In [3]:
my_tensor = torch.arange(6).reshape(3,2)
my_tensor

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
my_tensor[1,1]

tensor(3)

In [5]:
my_tensor[1][1]

tensor(3)

In [6]:
type(my_tensor[1,1])

torch.Tensor

In [9]:
my_tensor[:,1]

tensor([1, 3, 5])

In [14]:
my_tensor[:,1:]

tensor([[1],
        [3],
        [5]])

In [15]:
x = torch.arange(10)

In [16]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
z = x.view(2,5) # view() takes effect to z (copied by x)

In [21]:
x[0] = 9999

In [22]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [28]:
x = torch.arange(10) 

In [29]:
x.view(2,-1) # need to be /2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [37]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
a = torch.tensor([1.,2,3.])
a.dtype

torch.float32

In [41]:
a = torch.tensor([1,2,3])
b= torch.tensor([4,5,6])
a

tensor([1, 2, 3])

In [42]:
b

tensor([4, 5, 6])

In [45]:
torch.add(a,b)

tensor([5, 7, 9])

In [46]:
a = a.mul(b)
a
# a = a + b 

tensor([ 4, 10, 18])