In [1]:
import torch

In [3]:
import numpy as np 

In [5]:
torch.__version__

'1.12.1+cu116'

In [8]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
arr.dtype

dtype('int64')

In [12]:
x = torch.from_numpy(arr)

In [13]:
type(x)

torch.Tensor

In [16]:
torch.as_tensor(arr).dtype

torch.int64

In [19]:
arr2d = np.arange(0.0,12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
arr2d.reshape(4,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [24]:
x2 = torch.from_numpy(arr2d)
x2

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [25]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
my_tensor = torch.Tensor(my_arr) # no take effected by numpy array
my_other_tensor = torch.from_numpy(my_arr) # take effected by numpy array

In [42]:
my_other_tensor

tensor([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [41]:
my_arr[0] =12

In [43]:
my_tensor

tensor([99.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])